# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "PlantSing" do
pod 'ORSSerialPort', '~> 1.0.3'
pod 'SoundManager', '~>1.4.1'

end

target "PlantSingTests" do

end

